### ISSUE TITLE
Mario Bros: Collision is off by one tile

### ISSUE THREAD

**Issue by sarospa** [sarospa/arachNES#2]
When hitting the POW block or a floor tile from underneath, Mario's collision hitbox seems to be off by one tile. This can be demonstrated by trying to hit the right side of the POW block. Note that even in correct emulation, only the center of Mario's head bumps tiles, as can be seen by checking how it behaves in FCEUX. Even accounting for this, in arachNES Mario collides with tiles as though he is displaced about one tile to the right.

**Comment by aiviru** [comment]
Just a test message, nothing to see here.
[This is a file.txt](https://github.com/sarospa/arachNES/files/591042/This.is.a.file.txt)

**Comment by sarospa** [comment]
Looks like I found the problem here. Should be fixed now.
