### ISSUE TITLE
Including SDL2.dll in the repository but not the headers is pointless.

### ISSUE THREAD

**Issue by TechnoMancer** [sarospa/arachNES#8]
Building the code will require the SDL2 development files which includes the headers and the import library for the DLL. As such including the DLL itself in the repository is of little use and it would be better to just say SDL2 is needed for building.

**Comment by sarospa** [comment]
I suppose that's a good point. It seemed like a good idea at the time, but then I'm still kinda figuring this stuff out. SDL2.dll removed from the project.
